name : Red Sox Powerball
brand : RSP
description : Moneyball with the local nine! My 2018 Baseball Hack Day submission
keyword : 
url : http://daigofuji.github.io/redsox-powerball/
email : daigo@daigofujiwara.com
twitter : DaigoFuji
github : DaigoFuji
author : Daigo Fujiwara
year : 2018
markdown : kramdown
exclude :
  - node_modules
